version: '3.9'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: studentdb
      POSTGRES_USER: studentuser
      POSTGRES_PASSWORD: studentpass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - studentnet

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_NAME: studentdb
      DB_USER: studentuser
      DB_PASSWORD: studentpass
      DB_HOST: db
      DB_PORT: 5432
    networks:
      - studentnet

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - studentnet

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - cadvisor
    networks:
      - studentnet

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - studentnet

volumes:
  postgres_data:
  grafana-storage:

networks:
  studentnet:
